apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.service.name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app: {{ .Values.db.name }}
  ports:
  - port: {{ .Values.db.service.port }}
    targetPort: {{ .Values.db.service.targetPort }}
    protocol: TCP
  type: {{ .Values.db.service.type }}