apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rabbitmq.service.name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
  - name: mq-port
    port: {{ .Values.rabbitmq.service.port }}
    targetPort: {{ .Values.rabbitmq.service.targetPort }}
    protocol: TCP
  selector:
    app: {{ .Values.rabbitmq.name }}
  type: {{ .Values.rabbitmq.service.type }}