apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.rabbitmq.name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: {{ .Values.rabbitmq.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.rabbitmq.name }}
  replicas: {{ .Values.rabbitmq.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.rabbitmq.name }}
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: mq-container
        image: "{{ .Values.rabbitmq.image.repository }}:{{ .Values.rabbitmq.image.tag }}"
        imagePullPolicy: {{ .Values.rabbitmq.image.pullPolicy }}
        ports:
        - name: mq-port
          containerPort: 5672
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: {{ .Values.rabbitmq.env.user | quote }}
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: rmq-pass
        resources:
{{ toYaml .Values.rabbitmq.resources | indent 10 }}