apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  db-pass: {{ .Values.secrets.dbPassword }}
  rmq-pass: {{ .Values.secrets.rmqPassword }}